### ISSUE TITLE
Fails with Node.js 17

### ISSUE THREAD

**Issue by jesec** [vercel/ncc#805]
Bug: webpack/webpack#14532

**Comment by styfle** [comment]
Fixed in #809

**Comment by jesec** [comment]
For some reasons, #809 and 0.32.0 does not resolve the issue.

```
ncc: Version 0.32.0
ncc: Compiling file index.js into CJS
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at hashOf (/home/jc/flood/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1890023)
    at ncc (/home/jc/flood/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1894488)
    at runCmd (/home/jc/flood/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:52268)
    at Object.819 (/home/jc/flood/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:48838)
    at __webpack_require__ (/home/jc/flood/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59076)
    at /home/jc/flood/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59288
    at /home/jc/flood/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59349
    at Object.<anonymous> (/home/jc/flood/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by jesec** [comment]
The issue may have something to do with ncc's failure to bundle the WebAssembly modules. I encounter some issues with the WebAssembly modules in the past. However, in this case, the issue could prevent webpack from using its own hash implementation:

https://github.com/webpack/webpack/tree/main/assembly/hash

This could become a bigger problem in next version of webpack, since xxhash64 would become default, and there is no OpenSSL implementation to fallback to.

**Comment by styfle** [comment]
Can you share steps to reproduce the issue? Then @sokra can take a look too.

**Comment by jesec** [comment]
It is very simple. 

Install Node v17, and run ncc on any project.

**Comment by styfle** [comment]
I see. There’s a PR to add Node 16 support https://github.com/vercel/ncc/pull/801

I haven’t tried Node 17 yet but it looks like the hash algo used is not supported by crypto.createHash()

**Comment by denik1981** [comment]
Any news with this? I can confirm the problem is with Node 17. 
Seems to be working well with Node 16.

**Comment by Piszmog** [comment]
I was able to get it to work with Node 17 with a hacky workaround,

I added the following to my scripts in `package.json`

`"buildv17": "node --openssl-legacy-provider ./node_modules/@vercel/ncc/dist/ncc/cli.js build"`

**Comment by Caikekeweb** [comment]
根目录新建.bashrc 文件，加入以下代码就可以了

# Windows 下，使用 set 命令：
set NODE_OPTIONS=--openssl-legacy-provider

# Linux 或 macOS 下，使用 export 命令：
export NODE_OPTIONS="--openssl-legacy-provider"
